M48
; DRILL file {KiCad 9.0.7} date 2026-04-09T21:45:01-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-09T21:45:01-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X52.15Y-104.95
X52.2Y-53.8
X52.2Y-78.2
X118.6Y-53.8
X118.6Y-78.2
X118.6Y-105.0
M30
